# Generated by Django 6.0.5 on 2026-05-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='systemfeature',
            options={'ordering': ['category', 'key'], 'verbose_name': 'System Feature', 'verbose_name_plural': 'System Features'},
        ),
        migrations.AddField(
            model_name='systemfeature',
            name='category',
            field=models.CharField(choices=[('ai', 'AI Engine'), ('seo', 'SEO System'), ('performance', 'Performance'), ('monitoring', 'Monitoring'), ('experimental', 'Experimental')], default='ai', max_length=50),
        ),
        migrations.AddField(
            model_name='systemfeature',
            name='cpu_intensive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemfeature',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='systemfeature',
            name='experimental',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemfeature',
            name='name',
            field=models.CharField(default='Feature', max_length=150),
        ),
    ]
