# Generated by Django 6.0.5 on 2026-05-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('intent', models.CharField(blank=True, max_length=100, null=True)),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=255, null=True)),
                ('seo_score', models.FloatField(default=0)),
                ('competition_score', models.FloatField(default=0)),
                ('quality_score', models.FloatField(default=0)),
                ('publish_score', models.FloatField(default=0)),
                ('should_generate', models.BooleanField(default=True)),
                ('rewrite_required', models.BooleanField(default=False)),
                ('execution_time', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('processing', 'Processing')], default='success', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Decision Log',
                'verbose_name_plural': 'Decision Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
