# Generated by Django 6.0.5 on 2026-05-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionlog',
            name='ai_quality_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='estimated_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='generation_success',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='provider_latency',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='response_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='decisionlog',
            name='token_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='decisionlog',
            index=models.Index(fields=['provider'], name='decision_en_provide_5b7f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionlog',
            index=models.Index(fields=['status'], name='decision_en_status_c1dded_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionlog',
            index=models.Index(fields=['created_at'], name='decision_en_created_b8b1b4_idx'),
        ),
        migrations.AddIndex(
            model_name='decisionlog',
            index=models.Index(fields=['publish_score'], name='decision_en_publish_e73a22_idx'),
        ),
    ]
