# Generated by Django 6.0.5 on 2026-05-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratorConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('active_provider', models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini'), ('ollama', 'Ollama')], default='gemini', max_length=50)),
                ('default_model', models.CharField(default='gemini-2.0-flash', max_length=100)),
                ('temperature', models.FloatField(default=0.7)),
                ('max_tokens', models.IntegerField(default=2000)),
                ('enable_memory', models.BooleanField(default=True)),
                ('enable_scoring', models.BooleanField(default=True)),
                ('enable_cleaning', models.BooleanField(default=True)),
                ('enable_fallback', models.BooleanField(default=True)),
                ('system_prompt', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Generator Config',
                'verbose_name_plural': 'Generator Configs',
            },
        ),
    ]
