# Generated by Django 6.0.5 on 2026-05-14 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generatorconfig',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Generator Config', 'verbose_name_plural': 'Generator Configs'},
        ),
        migrations.AddField(
            model_name='generatorconfig',
            name='content_type',
            field=models.CharField(choices=[('article', 'Article'), ('blog', 'Blog'), ('seo', 'SEO Content'), ('rewrite', 'Rewrite'), ('summary', 'Summary'), ('social', 'Social Post')], default='article', max_length=50),
        ),
        migrations.AddField(
            model_name='generatorconfig',
            name='enable_seo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='generatorconfig',
            name='max_rewrite_loops',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='generatorconfig',
            name='minimum_quality_score',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='generatorconfig',
            name='prompt_template',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generatorconfig',
            name='target_word_count',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='generatorconfig',
            name='tone',
            field=models.CharField(choices=[('professional', 'Professional'), ('casual', 'Casual'), ('humanized', 'Humanized'), ('technical', 'Technical'), ('marketing', 'Marketing')], default='humanized', max_length=50),
        ),
    ]
