# Generated by Django 6.0.5 on 2026-05-10 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engine', '0003_article_rewrite_quality_status_article_rewrite_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wordpress_post_id', models.CharField(blank=True, max_length=255, null=True)),
                ('wordpress_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('publish_attempts', models.PositiveIntegerField(default=0)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_posts', to='engine.article')),
            ],
            options={
                'verbose_name': 'Published Post',
                'verbose_name_plural': 'Published Posts',
                'ordering': ['-created_at'],
            },
        ),
    ]
