# Generated by Django 6.0.5 on 2026-05-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_article_rewrite_quality_status_article_rewrite_score_and_more'),
        ('publisher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishedpost',
            name='error_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='publishedpost',
            name='last_error_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publishedpost',
            name='provider',
            field=models.CharField(choices=[('wordpress', 'WordPress')], default='wordpress', max_length=50),
        ),
        migrations.AddField(
            model_name='publishedpost',
            name='publish_duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publishedpost',
            name='publish_method',
            field=models.CharField(default='rest_api', max_length=50),
        ),
        migrations.AlterField(
            model_name='publishedpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('draft', 'Draft'), ('published', 'Published'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='publishedpost',
            index=models.Index(fields=['status'], name='publisher_p_status_7c7305_idx'),
        ),
        migrations.AddIndex(
            model_name='publishedpost',
            index=models.Index(fields=['created_at'], name='publisher_p_created_70d559_idx'),
        ),
        migrations.AddIndex(
            model_name='publishedpost',
            index=models.Index(fields=['published_at'], name='publisher_p_publish_c1135c_idx'),
        ),
        migrations.AddConstraint(
            model_name='publishedpost',
            constraint=models.UniqueConstraint(fields=('article', 'wordpress_post_id'), name='unique_article_publish'),
        ),
    ]
