# Generated by Django 6.0.5 on 2026-05-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_openai', models.BooleanField(default=True)),
                ('enable_gemini', models.BooleanField(default=True)),
                ('enable_ollama', models.BooleanField(default=True)),
                ('enable_memory', models.BooleanField(default=True)),
                ('enable_hot_memory', models.BooleanField(default=True)),
                ('enable_semantic_memory', models.BooleanField(default=True)),
                ('debug_logging', models.BooleanField(default=False)),
                ('provider_timeout', models.IntegerField(default=120)),
                ('max_retries', models.IntegerField(default=2)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
