# Generated by Django 6.0.5 on 2026-05-22 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='enable_ollama',
            field=models.BooleanField(default=False),
        ),
    ]
