# Generated by Django 6.0.5 on 2026-05-14 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, unique=True)),
                ('normalized_keyword', models.CharField(blank=True, max_length=255)),
                ('search_intent', models.CharField(choices=[('informational', 'Informational'), ('commercial', 'Commercial'), ('transactional', 'Transactional'), ('navigational', 'Navigational')], default='informational', max_length=50)),
                ('seo_difficulty', models.IntegerField(default=0)),
                ('search_volume', models.IntegerField(default=0)),
                ('keyword_score', models.FloatField(default=0.0)),
                ('competition_level', models.CharField(blank=True, max_length=50, null=True)),
                ('related_keywords', models.JSONField(blank=True, default=list)),
                ('entities', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('recommended_content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('target_audience', models.CharField(blank=True, max_length=255, null=True)),
                ('is_trending', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Keyword Analysis',
                'verbose_name_plural': 'Keyword Analyses',
                'ordering': ['-updated_at'],
            },
        ),
    ]
