# Generated by Django 6.0.5 on 2026-05-17 06:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordanalysis',
            name='competition_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='keywordanalysis',
            name='is_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='keywordanalysis',
            name='language',
            field=models.CharField(db_index=True, default='english', max_length=20),
        ),
        migrations.AddField(
            model_name='keywordanalysis',
            name='last_analyzed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='keywordanalysis',
            name='recommended_word_count',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='keywordanalysis',
            name='semantic_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='keywordanalysis',
            name='total_analyses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='keywordanalysis',
            name='trend_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='keywordanalysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='keywordanalysis',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='keywordanalysis',
            name='is_trending',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='keywordanalysis',
            name='keyword',
            field=models.CharField(db_index=True, max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='keywordanalysis',
            name='keyword_score',
            field=models.FloatField(db_index=True, default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='keywordanalysis',
            name='normalized_keyword',
            field=models.CharField(db_index=True, editable=False, max_length=150),
        ),
        migrations.AlterField(
            model_name='keywordanalysis',
            name='search_intent',
            field=models.CharField(choices=[('informational', 'Informational'), ('commercial', 'Commercial'), ('transactional', 'Transactional'), ('navigational', 'Navigational'), ('comparison', 'Comparison'), ('local', 'Local')], db_index=True, default='informational', max_length=50),
        ),
        migrations.AlterField(
            model_name='keywordanalysis',
            name='search_volume',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='keywordanalysis',
            name='seo_difficulty',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], db_index=True, default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='keywordanalysis',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='keywordanalysis',
            index=models.Index(fields=['normalized_keyword'], name='keywords_ke_normali_3f4667_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordanalysis',
            index=models.Index(fields=['search_intent'], name='keywords_ke_search__731e71_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordanalysis',
            index=models.Index(fields=['keyword_score'], name='keywords_ke_keyword_71a4d2_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordanalysis',
            index=models.Index(fields=['is_trending'], name='keywords_ke_is_tren_687fd9_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordanalysis',
            index=models.Index(fields=['updated_at'], name='keywords_ke_updated_eafff5_idx'),
        ),
    ]
