# Generated by Django 6.0.5 on 2026-05-17 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0002_keywordanalysis_competition_score_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keywordanalysis',
            options={'get_latest_by': 'updated_at', 'ordering': ['-updated_at'], 'verbose_name': 'Keyword Analysis', 'verbose_name_plural': 'Keyword Analyses'},
        ),
        migrations.AddField(
            model_name='keywordanalysis',
            name='cache_key',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name='keywordanalysis',
            index=models.Index(fields=['cache_key'], name='keywords_ke_cache_k_98619b_idx'),
        ),
        migrations.AddConstraint(
            model_name='keywordanalysis',
            constraint=models.CheckConstraint(condition=models.Q(('keyword_score__gte', 0), ('keyword_score__lte', 100)), name='keyword_score_valid'),
        ),
        migrations.AddConstraint(
            model_name='keywordanalysis',
            constraint=models.CheckConstraint(condition=models.Q(('search_volume__gte', 0)), name='search_volume_valid'),
        ),
    ]
