# Generated by Django 6.0.5 on 2026-05-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0003_alter_keywordanalysis_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='keywordanalysis',
            index=models.Index(fields=['seo_difficulty'], name='keywords_ke_seo_dif_2d7e8d_idx'),
        ),
    ]
