# Generated by Django 6.0.5 on 2026-05-20 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keywords', '0004_keywordanalysis_keywords_ke_seo_dif_2d7e8d_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordResearchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, max_length=255)),
                ('normalized_keyword', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=50)),
                ('progress', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Keyword Research Job',
                'verbose_name_plural': 'Keyword Research Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='keywordanalysis',
            name='keyword_score_valid',
        ),
        migrations.RemoveConstraint(
            model_name='keywordanalysis',
            name='search_volume_valid',
        ),
        migrations.RemoveIndex(
            model_name='keywordanalysis',
            name='keywords_ke_normali_3f4667_idx',
        ),
        migrations.RemoveIndex(
            model_name='keywordanalysis',
            name='keywords_ke_search__731e71_idx',
        ),
        migrations.RemoveIndex(
            model_name='keywordanalysis',
            name='keywords_ke_keyword_71a4d2_idx',
        ),
        migrations.RemoveIndex(
            model_name='keywordanalysis',
            name='keywords_ke_is_tren_687fd9_idx',
        ),
        migrations.RemoveIndex(
            model_name='keywordanalysis',
            name='keywords_ke_updated_eafff5_idx',
        ),
        migrations.RemoveIndex(
            model_name='keywordanalysis',
            name='keywords_ke_cache_k_98619b_idx',
        ),
        migrations.RemoveIndex(
            model_name='keywordanalysis',
            name='keywords_ke_seo_dif_2d7e8d_idx',
        ),
        migrations.AddField(
            model_name='keywordanalysis',
            name='cluster_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='keywordanalysis',
            name='competitor_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='keywordanalysis',
            name='outline_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='keywordanalysis',
            name='people_also_ask',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='keywordanalysis',
            name='recommendation_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='keywordanalysis',
            name='related_searches',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='keywordanalysis',
            name='competition_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='keywordanalysis',
            name='trend_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='keywordresearchjob',
            index=models.Index(fields=['status'], name='keywords_ke_status_e7aef6_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordresearchjob',
            index=models.Index(fields=['created_at'], name='keywords_ke_created_829231_idx'),
        ),
        migrations.AddIndex(
            model_name='keywordresearchjob',
            index=models.Index(fields=['normalized_keyword'], name='keywords_ke_normali_c1e79f_idx'),
        ),
    ]
