# Generated by Django 6.0.5 on 2026-05-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_article_conclusion_article_faq_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rewrite_quality_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='rewrite_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='rewritten',
            field=models.BooleanField(default=False),
        ),
    ]
