# Generated by Django 6.0.5 on 2026-05-14 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engineexecution',
            options={'ordering': ['-created_at'], 'verbose_name': 'Engine Execution', 'verbose_name_plural': 'Engine Executions'},
        ),
        migrations.AddField(
            model_name='engineexecution',
            name='cpu_usage_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='engineexecution',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='engineexecution',
            name='memory_usage_mb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='engineexecution',
            name='model_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='engineexecution',
            name='provider',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='engineexecution',
            name='task_type',
            field=models.CharField(default='article', max_length=100),
        ),
        migrations.AddField(
            model_name='engineexecution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='engineexecution',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('processing', 'Processing'), ('pending', 'Pending')], default='success', max_length=50),
        ),
    ]
