# Generated by Django 6.0.5 on 2026-05-14 03:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_alter_engineexecution_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Error Log', 'verbose_name_plural': 'Error Logs'},
        ),
        migrations.AlterModelOptions(
            name='featuretoggle',
            options={'ordering': ['name'], 'verbose_name': 'Feature Toggle', 'verbose_name_plural': 'Feature Toggles'},
        ),
        migrations.AddField(
            model_name='apirequestlog',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apirequestlog',
            name='query_params',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apirequestlog',
            name='response_size_kb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='apirequestlog',
            name='successful',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='apirequestlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='ip_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='method',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='errorlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='featuretoggle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='featuretoggle',
            name='environment',
            field=models.CharField(default='production', max_length=50),
        ),
        migrations.AddField(
            model_name='featuretoggle',
            name='updated_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='apirequestlog',
            name='method',
            field=models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=20),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='error', max_length=50),
        ),
        migrations.AlterField(
            model_name='errorlog',
            name='traceback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
