# Generated by Django 6.0.5 on 2026-05-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationhistory',
            name='completion_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generationhistory',
            name='content_length',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generationhistory',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generationhistory',
            name='estimated_cost',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='generationhistory',
            name='execution_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='generationhistory',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='generationhistory',
            name='model_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='generationhistory',
            name='normalized_query',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='generationhistory',
            name='prompt_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generationhistory',
            name='retry_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generationhistory',
            name='total_tokens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='generationhistory',
            name='traceback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='generationhistory',
            name='provider',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generationhistory',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('retrying', 'Retrying')], db_index=True, default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='generationhistory',
            name='task_type',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AddIndex(
            model_name='generationhistory',
            index=models.Index(fields=['task_id'], name='history_gen_task_id_51d9e3_idx'),
        ),
        migrations.AddIndex(
            model_name='generationhistory',
            index=models.Index(fields=['task_type'], name='history_gen_task_ty_42c061_idx'),
        ),
        migrations.AddIndex(
            model_name='generationhistory',
            index=models.Index(fields=['provider'], name='history_gen_provide_2387ce_idx'),
        ),
        migrations.AddIndex(
            model_name='generationhistory',
            index=models.Index(fields=['status'], name='history_gen_status_d6c30b_idx'),
        ),
        migrations.AddIndex(
            model_name='generationhistory',
            index=models.Index(fields=['-created_at'], name='history_gen_created_e6df28_idx'),
        ),
    ]
