# Generated by Django 6.0.5 on 2026-05-10 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('engine', '0003_article_rewrite_quality_status_article_rewrite_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=100)),
                ('total_requests', models.IntegerField(default=0)),
                ('successful_requests', models.IntegerField(default=0)),
                ('failed_requests', models.IntegerField(default=0)),
                ('average_response_time', models.FloatField(default=0)),
                ('average_quality_score', models.FloatField(default=0)),
                ('total_fallbacks', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, max_length=100, null=True)),
                ('generation_time', models.FloatField(default=0)),
                ('used_fallback', models.BooleanField(default=False)),
                ('rewrite_score', models.IntegerField(default=0)),
                ('readability_score', models.IntegerField(default=0)),
                ('engagement_score', models.IntegerField(default=0)),
                ('ai_detection_score', models.IntegerField(default=0)),
                ('verification_score', models.IntegerField(default=0)),
                ('verified_claims', models.IntegerField(default=0)),
                ('flagged_claims', models.IntegerField(default=0)),
                ('seo_score', models.IntegerField(default=0)),
                ('keyword_density', models.FloatField(default=0)),
                ('word_count', models.IntegerField(default=0)),
                ('published', models.BooleanField(default=False)),
                ('publish_url', models.URLField(blank=True, null=True)),
                ('error_count', models.IntegerField(default=0)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('final_quality_score', models.IntegerField(default=0)),
                ('quality_status', models.CharField(default='unknown', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='engine.article')),
            ],
        ),
    ]
