# Generated by Django 6.0.5 on 2026-05-14 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('generator', '0002_alter_generatorconfig_options_and_more'),
        ('keywords', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleanalytics',
            options={'ordering': ['-created_at'], 'verbose_name': 'Article Analytics', 'verbose_name_plural': 'Article Analytics'},
        ),
        migrations.AlterModelOptions(
            name='provideranalytics',
            options={'ordering': ['provider_name'], 'verbose_name': 'Provider Analytics', 'verbose_name_plural': 'Provider Analytics'},
        ),
        migrations.AddField(
            model_name='articleanalytics',
            name='estimated_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='articleanalytics',
            name='generator_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.generatorconfig'),
        ),
        migrations.AddField(
            model_name='articleanalytics',
            name='heading_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articleanalytics',
            name='keyword_analysis',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_analytics', to='keywords.keywordanalysis'),
        ),
        migrations.AddField(
            model_name='articleanalytics',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='articleanalytics',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='articleanalytics',
            name='raw_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='articleanalytics',
            name='response_latency',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='articleanalytics',
            name='retry_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='articleanalytics',
            name='token_usage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='provideranalytics',
            name='healthy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='provideranalytics',
            name='last_failure',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provideranalytics',
            name='last_success',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provideranalytics',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provideranalytics',
            name='uptime_percentage',
            field=models.FloatField(default=100),
        ),
        migrations.AlterField(
            model_name='articleanalytics',
            name='quality_status',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], default='average', max_length=50),
        ),
        migrations.AlterField(
            model_name='provideranalytics',
            name='provider_name',
            field=models.CharField(choices=[('openai', 'OpenAI'), ('gemini', 'Gemini'), ('ollama', 'Ollama')], max_length=100, unique=True),
        ),
    ]
